[package]
name = "sunny"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.4.1"
num-bigint = { version = "0.4.4", features = ["rand"] }
rand = "0.8.5"
